import Head from 'next/head';

// IMPORT COMPONENTS
import Header from '../components/Header';
import Footer from '../components/Footer';

export default function Home() {
  return (
    <div className="home">
      <Head>
        <title>Paléo H2O</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Footer />
    </div>
  )
}
